'\" t
.\"     Title: git-http-fetch
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-HTTP\-FETCH" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-http-fetch \- Download from a remote Git repository via HTTP
.SH "SYNOPSIS"
.sp
.nf
\fIgit http\-fetch\fR [\-c] [\-t] [\-a] [\-d] [\-v] [\-w filename] [\-\-recover] [\-\-stdin] <commit> <url>
.fi
.sp
.SH "DESCRIPTION"
.sp
Downloads a remote Git repository via HTTP\&.
.sp
\fBNOTE\fR: use of this command without \-a is deprecated\&. The \-a behaviour will become the default in a future release\&.
.SH "OPTIONS"
.PP
commit\-id
.RS 4
Either the hash or the filename under [URL]/refs/ to pull\&.
.RE
.PP
\-c
.RS 4
Get the commit objects\&.
.RE
.PP
\-t
.RS 4
Get trees associated with the commit objects\&.
.RE
.PP
\-a
.RS 4
Get all the objects\&.
.RE
.PP
\-v
.RS 4
Report what is downloaded\&.
.RE
.PP
\-w <filename>
.RS 4
Writes the commit\-id into the filename under $GIT_DIR/refs/<filename> on the local end after the transfer is complete\&.
.RE
.PP
\-\-stdin
.RS 4
Instead of a commit id on the command line (which is not expected in this case),
\fIgit http\-fetch\fR
expects lines on stdin in the format
.sp
.if n \{\
.RS 4
.\}
.nf
<commit\-id>[\(aq\et\(aq<filename\-as\-in\-\-w>]
.fi
.if n \{\
.RE
.\}
.RE
.PP
\-\-recover
.RS 4
Verify that everything reachable from target is fetched\&. Used after an earlier fetch is interrupted\&.
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
