'\" t
.\"     Title: git-rebase
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-REBASE" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-rebase \- Reapply commits on top of another base tip
.SH "SYNOPSIS"
.sp
.nf
\fIgit rebase\fR [\-i | \-\-interactive] [options] [\-\-exec <cmd>] [\-\-onto <newbase>]
        [<upstream> [<branch>]]
\fIgit rebase\fR [\-i | \-\-interactive] [options] [\-\-exec <cmd>] [\-\-onto <newbase>]
        \-\-root [<branch>]
\fIgit rebase\fR \-\-continue | \-\-skip | \-\-abort | \-\-quit | \-\-edit\-todo | \-\-show\-current\-patch
.fi
.sp
.SH "DESCRIPTION"
.sp
If <branch> is specified, \fIgit rebase\fR will perform an automatic \fBgit checkout <branch>\fR before doing anything else\&. Otherwise it remains on the current branch\&.
.sp
If <upstream> is not specified, the upstream configured in branch\&.<name>\&.remote and branch\&.<name>\&.merge options will be used (see \fBgit-config\fR(1) for details) and the \fB\-\-fork\-point\fR option is assumed\&. If you are currently not on any branch or if the current branch does not have a configured upstream, the rebase will abort\&.
.sp
All changes made by commits in the current branch but that are not in <upstream> are saved to a temporary area\&. This is the same set of commits that would be shown by \fBgit log <upstream>\&.\&.HEAD\fR; or by \fBgit log \(aqfork_point\(aq\&.\&.HEAD\fR, if \fB\-\-fork\-point\fR is active (see the description on \fB\-\-fork\-point\fR below); or by \fBgit log HEAD\fR, if the \fB\-\-root\fR option is specified\&.
.sp
The current branch is reset to <upstream>, or <newbase> if the \-\-onto option was supplied\&. This has the exact same effect as \fBgit reset \-\-hard <upstream>\fR (or <newbase>)\&. ORIG_HEAD is set to point at the tip of the branch before the reset\&.
.sp
The commits that were previously saved into the temporary area are then reapplied to the current branch, one by one, in order\&. Note that any commits in HEAD which introduce the same textual changes as a commit in HEAD\&.\&.<upstream> are omitted (i\&.e\&., a patch already accepted upstream with a different commit message or timestamp will be skipped)\&.
.sp
It is possible that a merge failure will prevent this process from being completely automatic\&. You will have to resolve any such merge failure and run \fBgit rebase \-\-continue\fR\&. Another option is to bypass the commit that caused the merge failure with \fBgit rebase \-\-skip\fR\&. To check out the original <branch> and remove the \&.git/rebase\-apply working files, use the command \fBgit rebase \-\-abort\fR instead\&.
.sp
Assume the following history exists and the current branch is "topic":
.sp
.if n \{\
.RS 4
.\}
.nf
          A\-\-\-B\-\-\-C topic
         /
    D\-\-\-E\-\-\-F\-\-\-G master
.fi
.if n \{\
.RE
.\}
.sp
.sp
From this point, the result of either of the following commands:
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase master
git rebase master topic
.fi
.if n \{\
.RE
.\}
.sp
would be:
.sp
.if n \{\
.RS 4
.\}
.nf
                  A\(aq\-\-B\(aq\-\-C\(aq topic
                 /
    D\-\-\-E\-\-\-F\-\-\-G master
.fi
.if n \{\
.RE
.\}
.sp
.sp
\fBNOTE:\fR The latter form is just a short\-hand of \fBgit checkout topic\fR followed by \fBgit rebase master\fR\&. When rebase exits \fBtopic\fR will remain the checked\-out branch\&.
.sp
If the upstream branch already contains a change you have made (e\&.g\&., because you mailed a patch which was applied upstream), then that commit will be skipped\&. For example, running \fBgit rebase master\fR on the following history (in which \fBA\(aq\fR and \fBA\fR introduce the same set of changes, but have different committer information):
.sp
.if n \{\
.RS 4
.\}
.nf
          A\-\-\-B\-\-\-C topic
         /
    D\-\-\-E\-\-\-A\(aq\-\-\-F master
.fi
.if n \{\
.RE
.\}
.sp
.sp
will result in:
.sp
.if n \{\
.RS 4
.\}
.nf
                   B\(aq\-\-\-C\(aq topic
                  /
    D\-\-\-E\-\-\-A\(aq\-\-\-F master
.fi
.if n \{\
.RE
.\}
.sp
.sp
Here is how you would transplant a topic branch based on one branch to another, to pretend that you forked the topic branch from the latter branch, using \fBrebase \-\-onto\fR\&.
.sp
First let\(cqs assume your \fItopic\fR is based on branch \fInext\fR\&. For example, a feature developed in \fItopic\fR depends on some functionality which is found in \fInext\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
    o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  master
         \e
          o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  next
                           \e
                            o\-\-\-o\-\-\-o  topic
.fi
.if n \{\
.RE
.\}
.sp
.sp
We want to make \fItopic\fR forked from branch \fImaster\fR; for example, because the functionality on which \fItopic\fR depends was merged into the more stable \fImaster\fR branch\&. We want our tree to look like this:
.sp
.if n \{\
.RS 4
.\}
.nf
    o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  master
        |            \e
        |             o\(aq\-\-o\(aq\-\-o\(aq  topic
         \e
          o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  next
.fi
.if n \{\
.RE
.\}
.sp
.sp
We can get this using the following command:
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-\-onto master next topic
.fi
.if n \{\
.RE
.\}
.sp
Another example of \-\-onto option is to rebase part of a branch\&. If we have the following situation:
.sp
.if n \{\
.RS 4
.\}
.nf
                            H\-\-\-I\-\-\-J topicB
                           /
                  E\-\-\-F\-\-\-G  topicA
                 /
    A\-\-\-B\-\-\-C\-\-\-D  master
.fi
.if n \{\
.RE
.\}
.sp
.sp
then the command
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-\-onto master topicA topicB
.fi
.if n \{\
.RE
.\}
.sp
would result in:
.sp
.if n \{\
.RS 4
.\}
.nf
                 H\(aq\-\-I\(aq\-\-J\(aq  topicB
                /
                | E\-\-\-F\-\-\-G  topicA
                |/
    A\-\-\-B\-\-\-C\-\-\-D  master
.fi
.if n \{\
.RE
.\}
.sp
.sp
This is useful when topicB does not depend on topicA\&.
.sp
A range of commits could also be removed with rebase\&. If we have the following situation:
.sp
.if n \{\
.RS 4
.\}
.nf
    E\-\-\-F\-\-\-G\-\-\-H\-\-\-I\-\-\-J  topicA
.fi
.if n \{\
.RE
.\}
.sp
.sp
then the command
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-\-onto topicA~5 topicA~3 topicA
.fi
.if n \{\
.RE
.\}
.sp
would result in the removal of commits F and G:
.sp
.if n \{\
.RS 4
.\}
.nf
    E\-\-\-H\(aq\-\-\-I\(aq\-\-\-J\(aq  topicA
.fi
.if n \{\
.RE
.\}
.sp
.sp
This is useful if F and G were flawed in some way, or should not be part of topicA\&. Note that the argument to \-\-onto and the <upstream> parameter can be any valid commit\-ish\&.
.sp
In case of conflict, \fIgit rebase\fR will stop at the first problematic commit and leave conflict markers in the tree\&. You can use \fIgit diff\fR to locate the markers (<<<<<<) and make edits to resolve the conflict\&. For each file you edit, you need to tell Git that the conflict has been resolved, typically this would be done with
.sp
.if n \{\
.RS 4
.\}
.nf
git add <filename>
.fi
.if n \{\
.RE
.\}
.sp
After resolving the conflict manually and updating the index with the desired resolution, you can continue the rebasing process with
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-\-continue
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, you can undo the \fIgit rebase\fR with
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-\-abort
.fi
.if n \{\
.RE
.\}
.SH "CONFIGURATION"
.PP
rebase\&.stat
.RS 4
Whether to show a diffstat of what changed upstream since the last rebase\&. False by default\&.
.RE
.PP
rebase\&.autoSquash
.RS 4
If set to true enable
\fB\-\-autosquash\fR
option by default\&.
.RE
.PP
rebase\&.autoStash
.RS 4
When set to true, automatically create a temporary stash entry before the operation begins, and apply it after the operation ends\&. This means that you can run rebase on a dirty worktree\&. However, use with care: the final stash application after a successful rebase might result in non\-trivial conflicts\&. This option can be overridden by the
\fB\-\-no\-autostash\fR
and
\fB\-\-autostash\fR
options of
\fBgit-rebase\fR(1)\&. Defaults to false\&.
.RE
.PP
rebase\&.missingCommitsCheck
.RS 4
If set to "warn", git rebase \-i will print a warning if some commits are removed (e\&.g\&. a line was deleted), however the rebase will still proceed\&. If set to "error", it will print the previous warning and stop the rebase,
\fIgit rebase \-\-edit\-todo\fR
can then be used to correct the error\&. If set to "ignore", no checking is done\&. To drop a commit without warning or error, use the
\fBdrop\fR
command in the todo list\&. Defaults to "ignore"\&.
.RE
.PP
rebase\&.instructionFormat
.RS 4
A format string, as specified in
\fBgit-log\fR(1), to be used for the todo list during an interactive rebase\&. The format will automatically have the long commit hash prepended to the format\&.
.RE
.PP
rebase\&.abbreviateCommands
.RS 4
If set to true,
\fBgit rebase\fR
will use abbreviated command names in the todo list resulting in something like this:
.sp
.if n \{\
.RS 4
.\}
.nf
        p deadbee The oneline of the commit
        p fa1afe1 The oneline of the next commit
        \&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
instead of:
.sp
.if n \{\
.RS 4
.\}
.nf
        pick deadbee The oneline of the commit
        pick fa1afe1 The oneline of the next commit
        \&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
Defaults to false\&.
.RE
.SH "OPTIONS"
.PP
\-\-onto <newbase>
.RS 4
Starting point at which to create the new commits\&. If the \-\-onto option is not specified, the starting point is <upstream>\&. May be any valid commit, and not just an existing branch name\&.
.sp
As a special case, you may use "A\&.\&.\&.B" as a shortcut for the merge base of A and B if there is exactly one merge base\&. You can leave out at most one of A and B, in which case it defaults to HEAD\&.
.RE
.PP
<upstream>
.RS 4
Upstream branch to compare against\&. May be any valid commit, not just an existing branch name\&. Defaults to the configured upstream for the current branch\&.
.RE
.PP
<branch>
.RS 4
Working branch; defaults to HEAD\&.
.RE
.PP
\-\-continue
.RS 4
Restart the rebasing process after having resolved a merge conflict\&.
.RE
.PP
\-\-abort
.RS 4
Abort the rebase operation and reset HEAD to the original branch\&. If <branch> was provided when the rebase operation was started, then HEAD will be reset to <branch>\&. Otherwise HEAD will be reset to where it was when the rebase operation was started\&.
.RE
.PP
\-\-quit
.RS 4
Abort the rebase operation but HEAD is not reset back to the original branch\&. The index and working tree are also left unchanged as a result\&.
.RE
.PP
\-\-keep\-empty
.RS 4
Keep the commits that do not change anything from its parents in the result\&.
.RE
.PP
\-\-allow\-empty\-message
.RS 4
By default, rebasing commits with an empty message will fail\&. This option overrides that behavior, allowing commits with empty messages to be rebased\&.
.RE
.PP
\-\-skip
.RS 4
Restart the rebasing process by skipping the current patch\&.
.RE
.PP
\-\-edit\-todo
.RS 4
Edit the todo list during an interactive rebase\&.
.RE
.PP
\-\-show\-current\-patch
.RS 4
Show the current patch in an interactive rebase or when rebase is stopped because of conflicts\&. This is the equivalent of
\fBgit show REBASE_HEAD\fR\&.
.RE
.PP
\-m, \-\-merge
.RS 4
Use merging strategies to rebase\&. When the recursive (default) merge strategy is used, this allows rebase to be aware of renames on the upstream side\&.
.sp
Note that a rebase merge works by replaying each commit from the working branch on top of the <upstream> branch\&. Because of this, when a merge conflict happens, the side reported as
\fIours\fR
is the so\-far rebased series, starting with <upstream>, and
\fItheirs\fR
is the working branch\&. In other words, the sides are swapped\&.
.RE
.PP
\-s <strategy>, \-\-strategy=<strategy>
.RS 4
Use the given merge strategy\&. If there is no
\fB\-s\fR
option
\fIgit merge\-recursive\fR
is used instead\&. This implies \-\-merge\&.
.sp
Because
\fIgit rebase\fR
replays each commit from the working branch on top of the <upstream> branch using the given strategy, using the
\fIours\fR
strategy simply discards all patches from the <branch>, which makes little sense\&.
.RE
.PP
\-X <strategy\-option>, \-\-strategy\-option=<strategy\-option>
.RS 4
Pass the <strategy\-option> through to the merge strategy\&. This implies
\fB\-\-merge\fR
and, if no strategy has been specified,
\fB\-s recursive\fR\&. Note the reversal of
\fIours\fR
and
\fItheirs\fR
as noted above for the
\fB\-m\fR
option\&.
.RE
.PP
\-S[<keyid>], \-\-gpg\-sign[=<keyid>]
.RS 4
GPG\-sign commits\&. The
\fBkeyid\fR
argument is optional and defaults to the committer identity; if specified, it must be stuck to the option without a space\&.
.RE
.PP
\-q, \-\-quiet
.RS 4
Be quiet\&. Implies \-\-no\-stat\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Be verbose\&. Implies \-\-stat\&.
.RE
.PP
\-\-stat
.RS 4
Show a diffstat of what changed upstream since the last rebase\&. The diffstat is also controlled by the configuration option rebase\&.stat\&.
.RE
.PP
\-n, \-\-no\-stat
.RS 4
Do not show a diffstat as part of the rebase process\&.
.RE
.PP
\-\-no\-verify
.RS 4
This option bypasses the pre\-rebase hook\&. See also
\fBgithooks\fR(5)\&.
.RE
.PP
\-\-verify
.RS 4
Allows the pre\-rebase hook to run, which is the default\&. This option can be used to override \-\-no\-verify\&. See also
\fBgithooks\fR(5)\&.
.RE
.PP
\-C<n>
.RS 4
Ensure at least <n> lines of surrounding context match before and after each change\&. When fewer lines of surrounding context exist they all must match\&. By default no context is ever ignored\&.
.RE
.PP
\-f, \-\-force\-rebase
.RS 4
Force a rebase even if the current branch is up to date and the command without
\fB\-\-force\fR
would return without doing anything\&.
.sp
You may find this (or \-\-no\-ff with an interactive rebase) helpful after reverting a topic branch merge, as this option recreates the topic branch with fresh commits so it can be remerged successfully without needing to "revert the reversion" (see the
\m[blue]\fBrevert\-a\-faulty\-merge How\-To\fR\m[]\&\s-2\u[1]\d\s+2
for details)\&.
.RE
.PP
\-\-fork\-point, \-\-no\-fork\-point
.RS 4
Use reflog to find a better common ancestor between <upstream> and <branch> when calculating which commits have been introduced by <branch>\&.
.sp
When \-\-fork\-point is active,
\fIfork_point\fR
will be used instead of <upstream> to calculate the set of commits to rebase, where
\fIfork_point\fR
is the result of
\fBgit merge\-base \-\-fork\-point <upstream> <branch>\fR
command (see
\fBgit-merge-base\fR(1))\&. If
\fIfork_point\fR
ends up being empty, the <upstream> will be used as a fallback\&.
.sp
If either <upstream> or \-\-root is given on the command line, then the default is
\fB\-\-no\-fork\-point\fR, otherwise the default is
\fB\-\-fork\-point\fR\&.
.RE
.PP
\-\-ignore\-whitespace, \-\-whitespace=<option>
.RS 4
These flag are passed to the
\fIgit apply\fR
program (see
\fBgit-apply\fR(1)) that applies the patch\&. Incompatible with the \-\-interactive option\&.
.RE
.PP
\-\-committer\-date\-is\-author\-date, \-\-ignore\-date
.RS 4
These flags are passed to
\fIgit am\fR
to easily change the dates of the rebased commits (see
\fBgit-am\fR(1))\&. Incompatible with the \-\-interactive option\&.
.RE
.PP
\-\-signoff
.RS 4
This flag is passed to
\fIgit am\fR
to sign off all the rebased commits (see
\fBgit-am\fR(1))\&. Incompatible with the \-\-interactive option\&.
.RE
.PP
\-i, \-\-interactive
.RS 4
Make a list of the commits which are about to be rebased\&. Let the user edit that list before rebasing\&. This mode can also be used to split commits (see SPLITTING COMMITS below)\&.
.sp
The commit list format can be changed by setting the configuration option rebase\&.instructionFormat\&. A customized instruction format will automatically have the long commit hash prepended to the format\&.
.RE
.PP
\-p, \-\-preserve\-merges
.RS 4
Recreate merge commits instead of flattening the history by replaying commits a merge commit introduces\&. Merge conflict resolutions or manual amendments to merge commits are not preserved\&.
.sp
This uses the
\fB\-\-interactive\fR
machinery internally, but combining it with the
\fB\-\-interactive\fR
option explicitly is generally not a good idea unless you know what you are doing (see BUGS below)\&.
.RE
.PP
\-x <cmd>, \-\-exec <cmd>
.RS 4
Append "exec <cmd>" after each line creating a commit in the final history\&. <cmd> will be interpreted as one or more shell commands\&.
.sp
You may execute several commands by either using one instance of
\fB\-\-exec\fR
with several commands:
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-i \-\-exec "cmd1 && cmd2 && \&.\&.\&."
.fi
.if n \{\
.RE
.\}
.sp
or by giving more than one
\fB\-\-exec\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-i \-\-exec "cmd1" \-\-exec "cmd2" \-\-exec \&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
If
\fB\-\-autosquash\fR
is used, "exec" lines will not be appended for the intermediate commits, and will only appear at the end of each squash/fixup series\&.
.sp
This uses the
\fB\-\-interactive\fR
machinery internally, but it can be run without an explicit
\fB\-\-interactive\fR\&.
.RE
.PP
\-\-root
.RS 4
Rebase all commits reachable from <branch>, instead of limiting them with an <upstream>\&. This allows you to rebase the root commit(s) on a branch\&. When used with \-\-onto, it will skip changes already contained in <newbase> (instead of <upstream>) whereas without \-\-onto it will operate on every change\&. When used together with both \-\-onto and \-\-preserve\-merges,
\fIall\fR
root commits will be rewritten to have <newbase> as parent instead\&.
.RE
.PP
\-\-autosquash, \-\-no\-autosquash
.RS 4
When the commit log message begins with "squash! \&..." (or "fixup! \&..."), and there is already a commit in the todo list that matches the same
\fB\&.\&.\&.\fR, automatically modify the todo list of rebase \-i so that the commit marked for squashing comes right after the commit to be modified, and change the action of the moved commit from
\fBpick\fR
to
\fBsquash\fR
(or
\fBfixup\fR)\&. A commit matches the
\fB\&.\&.\&.\fR
if the commit subject matches, or if the
\fB\&.\&.\&.\fR
refers to the commit\(cqs hash\&. As a fall\-back, partial matches of the commit subject work, too\&. The recommended way to create fixup/squash commits is by using the
\fB\-\-fixup\fR/\fB\-\-squash\fR
options of
\fBgit-commit\fR(1)\&.
.sp
This option is only valid when the
\fB\-\-interactive\fR
option is used\&.
.sp
If the
\fB\-\-autosquash\fR
option is enabled by default using the configuration variable
\fBrebase\&.autoSquash\fR, this option can be used to override and disable this setting\&.
.RE
.PP
\-\-autostash, \-\-no\-autostash
.RS 4
Automatically create a temporary stash entry before the operation begins, and apply it after the operation ends\&. This means that you can run rebase on a dirty worktree\&. However, use with care: the final stash application after a successful rebase might result in non\-trivial conflicts\&.
.RE
.PP
\-\-no\-ff
.RS 4
With \-\-interactive, cherry\-pick all rebased commits instead of fast\-forwarding over the unchanged ones\&. This ensures that the entire history of the rebased branch is composed of new commits\&.
.sp
Without \-\-interactive, this is a synonym for \-\-force\-rebase\&.
.sp
You may find this helpful after reverting a topic branch merge, as this option recreates the topic branch with fresh commits so it can be remerged successfully without needing to "revert the reversion" (see the
\m[blue]\fBrevert\-a\-faulty\-merge How\-To\fR\m[]\&\s-2\u[1]\d\s+2
for details)\&.
.RE
.SH "MERGE STRATEGIES"
.sp
The merge mechanism (\fBgit merge\fR and \fBgit pull\fR commands) allows the backend \fImerge strategies\fR to be chosen with \fB\-s\fR option\&. Some strategies can also take their own options, which can be passed by giving \fB\-X<option>\fR arguments to \fBgit merge\fR and/or \fBgit pull\fR\&.
.PP
resolve
.RS 4
This can only resolve two heads (i\&.e\&. the current branch and another branch you pulled from) using a 3\-way merge algorithm\&. It tries to carefully detect criss\-cross merge ambiguities and is considered generally safe and fast\&.
.RE
.PP
recursive
.RS 4
This can only resolve two heads using a 3\-way merge algorithm\&. When there is more than one common ancestor that can be used for 3\-way merge, it creates a merged tree of the common ancestors and uses that as the reference tree for the 3\-way merge\&. This has been reported to result in fewer merge conflicts without causing mismerges by tests done on actual merge commits taken from Linux 2\&.6 kernel development history\&. Additionally this can detect and handle merges involving renames\&. This is the default merge strategy when pulling or merging one branch\&.
.sp
The
\fIrecursive\fR
strategy can take the following options:
.PP
ours
.RS 4
This option forces conflicting hunks to be auto\-resolved cleanly by favoring
\fIour\fR
version\&. Changes from the other tree that do not conflict with our side are reflected to the merge result\&. For a binary file, the entire contents are taken from our side\&.
.sp
This should not be confused with the
\fIours\fR
merge strategy, which does not even look at what the other tree contains at all\&. It discards everything the other tree did, declaring
\fIour\fR
history contains all that happened in it\&.
.RE
.PP
theirs
.RS 4
This is the opposite of
\fIours\fR; note that, unlike
\fIours\fR, there is no
\fItheirs\fR
merge strategy to confuse this merge option with\&.
.RE
.PP
patience
.RS 4
With this option,
\fImerge\-recursive\fR
spends a little extra time to avoid mismerges that sometimes occur due to unimportant matching lines (e\&.g\&., braces from distinct functions)\&. Use this when the branches to be merged have diverged wildly\&. See also
\fBgit-diff\fR(1)
\fB\-\-patience\fR\&.
.RE
.PP
diff\-algorithm=[patience|minimal|histogram|myers]
.RS 4
Tells
\fImerge\-recursive\fR
to use a different diff algorithm, which can help avoid mismerges that occur due to unimportant matching lines (such as braces from distinct functions)\&. See also
\fBgit-diff\fR(1)
\fB\-\-diff\-algorithm\fR\&.
.RE
.PP
ignore\-space\-change, ignore\-all\-space, ignore\-space\-at\-eol, ignore\-cr\-at\-eol
.RS 4
Treats lines with the indicated type of whitespace change as unchanged for the sake of a three\-way merge\&. Whitespace changes mixed with other changes to a line are not ignored\&. See also
\fBgit-diff\fR(1)
\fB\-b\fR,
\fB\-w\fR,
\fB\-\-ignore\-space\-at\-eol\fR, and
\fB\-\-ignore\-cr\-at\-eol\fR\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If
\fItheir\fR
version only introduces whitespace changes to a line,
\fIour\fR
version is used;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If
\fIour\fR
version introduces whitespace changes but
\fItheir\fR
version includes a substantial change,
\fItheir\fR
version is used;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Otherwise, the merge proceeds in the usual way\&.
.RE
.RE
.PP
renormalize
.RS 4
This runs a virtual check\-out and check\-in of all three stages of a file when resolving a three\-way merge\&. This option is meant to be used when merging branches with different clean filters or end\-of\-line normalization rules\&. See "Merging branches with differing checkin/checkout attributes" in
\fBgitattributes\fR(5)
for details\&.
.RE
.PP
no\-renormalize
.RS 4
Disables the
\fBrenormalize\fR
option\&. This overrides the
\fBmerge\&.renormalize\fR
configuration variable\&.
.RE
.PP
no\-renames
.RS 4
Turn off rename detection\&. See also
\fBgit-diff\fR(1)
\fB\-\-no\-renames\fR\&.
.RE
.PP
find\-renames[=<n>]
.RS 4
Turn on rename detection, optionally setting the similarity threshold\&. This is the default\&. See also
\fBgit-diff\fR(1)
\fB\-\-find\-renames\fR\&.
.RE
.PP
rename\-threshold=<n>
.RS 4
Deprecated synonym for
\fBfind\-renames=<n>\fR\&.
.RE
.PP
subtree[=<path>]
.RS 4
This option is a more advanced form of
\fIsubtree\fR
strategy, where the strategy makes a guess on how two trees must be shifted to match with each other when merging\&. Instead, the specified path is prefixed (or stripped from the beginning) to make the shape of two trees to match\&.
.RE
.RE
.PP
octopus
.RS 4
This resolves cases with more than two heads, but refuses to do a complex merge that needs manual resolution\&. It is primarily meant to be used for bundling topic branch heads together\&. This is the default merge strategy when pulling or merging more than one branch\&.
.RE
.PP
ours
.RS 4
This resolves any number of heads, but the resulting tree of the merge is always that of the current branch head, effectively ignoring all changes from all other branches\&. It is meant to be used to supersede old development history of side branches\&. Note that this is different from the \-Xours option to the
\fIrecursive\fR
merge strategy\&.
.RE
.PP
subtree
.RS 4
This is a modified recursive strategy\&. When merging trees A and B, if B corresponds to a subtree of A, B is first adjusted to match the tree structure of A, instead of reading the trees at the same level\&. This adjustment is also done to the common ancestor tree\&.
.RE
.sp
With the strategies that use 3\-way merge (including the default, \fIrecursive\fR), if a change is made on both branches, but later reverted on one of the branches, that change will be present in the merged result; some people find this behavior confusing\&. It occurs because only the heads and the merge base are considered when performing a merge, not the individual commits\&. The merge algorithm therefore considers the reverted change as no change at all, and substitutes the changed version instead\&.
.SH "NOTES"
.sp
You should understand the implications of using \fIgit rebase\fR on a repository that you share\&. See also RECOVERING FROM UPSTREAM REBASE below\&.
.sp
When the git\-rebase command is run, it will first execute a "pre\-rebase" hook if one exists\&. You can use this hook to do sanity checks and reject the rebase if it isn\(cqt appropriate\&. Please see the template pre\-rebase hook script for an example\&.
.sp
Upon completion, <branch> will be the current branch\&.
.SH "INTERACTIVE MODE"
.sp
Rebasing interactively means that you have a chance to edit the commits which are rebased\&. You can reorder the commits, and you can remove them (weeding out bad or otherwise unwanted patches)\&.
.sp
The interactive mode is meant for this type of workflow:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
have a wonderful idea
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
hack on the code
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
prepare a series for submission
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
submit
.RE
.sp
where point 2\&. consists of several instances of
.sp
a) regular use
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
finish something worthy of a commit
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
commit
.RE
.sp
b) independent fixup
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
realize that something does not work
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
fix that
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
commit it
.RE
.sp
Sometimes the thing fixed in b\&.2\&. cannot be amended to the not\-quite perfect commit it fixes, because that commit is buried deeply in a patch series\&. That is exactly what interactive rebase is for: use it after plenty of "a"s and "b"s, by rearranging and editing commits, and squashing multiple commits into one\&.
.sp
Start it with the last commit you want to retain as\-is:
.sp
.if n \{\
.RS 4
.\}
.nf
git rebase \-i <after\-this\-commit>
.fi
.if n \{\
.RE
.\}
.sp
An editor will be fired up with all the commits in your current branch (ignoring merge commits), which come after the given commit\&. You can reorder the commits in this list to your heart\(cqs content, and you can remove them\&. The list looks more or less like this:
.sp
.if n \{\
.RS 4
.\}
.nf
pick deadbee The oneline of this commit
pick fa1afe1 The oneline of the next commit
\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
.sp
The oneline descriptions are purely for your pleasure; \fIgit rebase\fR will not look at them but at the commit names ("deadbee" and "fa1afe1" in this example), so do not delete or edit the names\&.
.sp
By replacing the command "pick" with the command "edit", you can tell \fIgit rebase\fR to stop after applying that commit, so that you can edit the files and/or the commit message, amend the commit, and continue rebasing\&.
.sp
If you just want to edit the commit message for a commit, replace the command "pick" with the command "reword"\&.
.sp
To drop a commit, replace the command "pick" with "drop", or just delete the matching line\&.
.sp
If you want to fold two or more commits into one, replace the command "pick" for the second and subsequent commits with "squash" or "fixup"\&. If the commits had different authors, the folded commit will be attributed to the author of the first commit\&. The suggested commit message for the folded commit is the concatenation of the commit messages of the first commit and of those with the "squash" command, but omits the commit messages of commits with the "fixup" command\&.
.sp
\fIgit rebase\fR will stop when "pick" has been replaced with "edit" or when a command fails due to merge errors\&. When you are done editing and/or resolving conflicts you can continue with \fBgit rebase \-\-continue\fR\&.
.sp
For example, if you want to reorder the last 5 commits, such that what was HEAD~4 becomes the new HEAD\&. To achieve that, you would call \fIgit rebase\fR like this:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git rebase \-i HEAD~5
.fi
.if n \{\
.RE
.\}
.sp
.sp
And move the first patch to the end of the list\&.
.sp
You might want to preserve merges, if you have a history like this:
.sp
.if n \{\
.RS 4
.\}
.nf
           X
            \e
         A\-\-\-M\-\-\-B
        /
\-\-\-o\-\-\-O\-\-\-P\-\-\-Q
.fi
.if n \{\
.RE
.\}
.sp
.sp
Suppose you want to rebase the side branch starting at "A" to "Q"\&. Make sure that the current HEAD is "B", and call
.sp
.if n \{\
.RS 4
.\}
.nf
$ git rebase \-i \-p \-\-onto Q O
.fi
.if n \{\
.RE
.\}
.sp
.sp
Reordering and editing commits usually creates untested intermediate steps\&. You may want to check that your history editing did not break anything by running a test, or at least recompiling at intermediate points in history by using the "exec" command (shortcut "x")\&. You may do so by creating a todo list like this one:
.sp
.if n \{\
.RS 4
.\}
.nf
pick deadbee Implement feature XXX
fixup f1a5c00 Fix to feature XXX
exec make
pick c0ffeee The oneline of the next commit
edit deadbab The oneline of the commit after
exec cd subdir; make test
\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
.sp
The interactive rebase will stop when a command fails (i\&.e\&. exits with non\-0 status) to give you an opportunity to fix the problem\&. You can continue with \fBgit rebase \-\-continue\fR\&.
.sp
The "exec" command launches the command in a shell (the one specified in \fB$SHELL\fR, or the default shell if \fB$SHELL\fR is not set), so you can use shell features (like "cd", ">", ";" \&...)\&. The command is run from the root of the working tree\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ git rebase \-i \-\-exec "make test"
.fi
.if n \{\
.RE
.\}
.sp
.sp
This command lets you check that intermediate commits are compilable\&. The todo list becomes like that:
.sp
.if n \{\
.RS 4
.\}
.nf
pick 5928aea one
exec make test
pick 04d0fda two
exec make test
pick ba46169 three
exec make test
pick f4593f9 four
exec make test
.fi
.if n \{\
.RE
.\}
.sp
.SH "SPLITTING COMMITS"
.sp
In interactive mode, you can mark commits with the action "edit"\&. However, this does not necessarily mean that \fIgit rebase\fR expects the result of this edit to be exactly one commit\&. Indeed, you can undo the commit, or you can add other commits\&. This can be used to split a commit into two:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Start an interactive rebase with
\fBgit rebase \-i <commit>^\fR, where <commit> is the commit you want to split\&. In fact, any commit range will do, as long as it contains that commit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mark the commit you want to split with the action "edit"\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
When it comes to editing that commit, execute
\fBgit reset HEAD^\fR\&. The effect is that the HEAD is rewound by one, and the index follows suit\&. However, the working tree stays the same\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Now add the changes to the index that you want to have in the first commit\&. You can use
\fBgit add\fR
(possibly interactively) or
\fIgit gui\fR
(or both) to do that\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Commit the now\-current index with whatever commit message is appropriate now\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Repeat the last two steps until your working tree is clean\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Continue the rebase with
\fBgit rebase \-\-continue\fR\&.
.RE
.sp
If you are not absolutely sure that the intermediate revisions are consistent (they compile, pass the testsuite, etc\&.) you should use \fIgit stash\fR to stash away the not\-yet\-committed changes after each commit, test, and amend the commit if fixes are necessary\&.
.SH "RECOVERING FROM UPSTREAM REBASE"
.sp
Rebasing (or any other form of rewriting) a branch that others have based work on is a bad idea: anyone downstream of it is forced to manually fix their history\&. This section explains how to do the fix from the downstream\(cqs point of view\&. The real fix, however, would be to avoid rebasing the upstream in the first place\&.
.sp
To illustrate, suppose you are in a situation where someone develops a \fIsubsystem\fR branch, and you are working on a \fItopic\fR that is dependent on this \fIsubsystem\fR\&. You might end up with a history like the following:
.sp
.if n \{\
.RS 4
.\}
.nf
    o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  master
         \e
          o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  subsystem
                           \e
                            *\-\-\-*\-\-\-*  topic
.fi
.if n \{\
.RE
.\}
.sp
.sp
If \fIsubsystem\fR is rebased against \fImaster\fR, the following happens:
.sp
.if n \{\
.RS 4
.\}
.nf
    o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  master
         \e                       \e
          o\-\-\-o\-\-\-o\-\-\-o\-\-\-o       o\(aq\-\-o\(aq\-\-o\(aq\-\-o\(aq\-\-o\(aq  subsystem
                           \e
                            *\-\-\-*\-\-\-*  topic
.fi
.if n \{\
.RE
.\}
.sp
.sp
If you now continue development as usual, and eventually merge \fItopic\fR to \fIsubsystem\fR, the commits from \fIsubsystem\fR will remain duplicated forever:
.sp
.if n \{\
.RS 4
.\}
.nf
    o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  master
         \e                       \e
          o\-\-\-o\-\-\-o\-\-\-o\-\-\-o       o\(aq\-\-o\(aq\-\-o\(aq\-\-o\(aq\-\-o\(aq\-\-M  subsystem
                           \e                         /
                            *\-\-\-*\-\-\-*\-\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\-*\-\-*  topic
.fi
.if n \{\
.RE
.\}
.sp
.sp
Such duplicates are generally frowned upon because they clutter up history, making it harder to follow\&. To clean things up, you need to transplant the commits on \fItopic\fR to the new \fIsubsystem\fR tip, i\&.e\&., rebase \fItopic\fR\&. This becomes a ripple effect: anyone downstream from \fItopic\fR is forced to rebase too, and so on!
.sp
There are two kinds of fixes, discussed in the following subsections:
.PP
Easy case: The changes are literally the same\&.
.RS 4
This happens if the
\fIsubsystem\fR
rebase was a simple rebase and had no conflicts\&.
.RE
.PP
Hard case: The changes are not the same\&.
.RS 4
This happens if the
\fIsubsystem\fR
rebase had conflicts, or used
\fB\-\-interactive\fR
to omit, edit, squash, or fixup commits; or if the upstream used one of
\fBcommit \-\-amend\fR,
\fBreset\fR, or
\fBfilter\-branch\fR\&.
.RE
.SS "The easy case"
.sp
Only works if the changes (patch IDs based on the diff contents) on \fIsubsystem\fR are literally the same before and after the rebase \fIsubsystem\fR did\&.
.sp
In that case, the fix is easy because \fIgit rebase\fR knows to skip changes that are already present in the new upstream\&. So if you say (assuming you\(cqre on \fItopic\fR)
.sp
.if n \{\
.RS 4
.\}
.nf
    $ git rebase subsystem
.fi
.if n \{\
.RE
.\}
.sp
.sp
you will end up with the fixed history
.sp
.if n \{\
.RS 4
.\}
.nf
    o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o\-\-\-o  master
                                 \e
                                  o\(aq\-\-o\(aq\-\-o\(aq\-\-o\(aq\-\-o\(aq  subsystem
                                                   \e
                                                    *\-\-\-*\-\-\-*  topic
.fi
.if n \{\
.RE
.\}
.sp
.SS "The hard case"
.sp
Things get more complicated if the \fIsubsystem\fR changes do not exactly correspond to the ones before the rebase\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
While an "easy case recovery" sometimes appears to be successful even in the hard case, it may have unintended consequences\&. For example, a commit that was removed via \fBgit rebase \-\-interactive\fR will be \fBresurrected\fR!
.sp .5v
.RE
.sp
The idea is to manually tell \fIgit rebase\fR "where the old \fIsubsystem\fR ended and your \fItopic\fR began", that is, what the old merge\-base between them was\&. You will have to find a way to name the last commit of the old \fIsubsystem\fR, for example:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
With the
\fIsubsystem\fR
reflog: after
\fIgit fetch\fR, the old tip of
\fIsubsystem\fR
is at
\fBsubsystem@{1}\fR\&. Subsequent fetches will increase the number\&. (See
\fBgit-reflog\fR(1)\&.)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Relative to the tip of
\fItopic\fR: knowing that your
\fItopic\fR
has three commits, the old tip of
\fIsubsystem\fR
must be
\fBtopic~3\fR\&.
.RE
.sp
You can then transplant the old \fBsubsystem\&.\&.topic\fR to the new tip by saying (for the reflog case, and assuming you are on \fItopic\fR already):
.sp
.if n \{\
.RS 4
.\}
.nf
    $ git rebase \-\-onto subsystem subsystem@{1}
.fi
.if n \{\
.RE
.\}
.sp
.sp
The ripple effect of a "hard case" recovery is especially bad: \fIeveryone\fR downstream from \fItopic\fR will now have to perform a "hard case" recovery too!
.SH "BUGS"
.sp
The todo list presented by \fB\-\-preserve\-merges \-\-interactive\fR does not represent the topology of the revision graph\&. Editing commits and rewording their commit messages should work fine, but attempts to reorder commits tend to produce counterintuitive results\&.
.sp
For example, an attempt to rearrange
.sp
.if n \{\
.RS 4
.\}
.nf
1 \-\-\- 2 \-\-\- 3 \-\-\- 4 \-\-\- 5
.fi
.if n \{\
.RE
.\}
.sp
.sp
to
.sp
.if n \{\
.RS 4
.\}
.nf
1 \-\-\- 2 \-\-\- 4 \-\-\- 3 \-\-\- 5
.fi
.if n \{\
.RE
.\}
.sp
.sp
by moving the "pick 4" line will result in the following history:
.sp
.if n \{\
.RS 4
.\}
.nf
        3
       /
1 \-\-\- 2 \-\-\- 4 \-\-\- 5
.fi
.if n \{\
.RE
.\}
.sp
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
.SH "NOTES"
.IP " 1." 4
revert-a-faulty-merge How-To
.RS 4
\%git-htmldocs/howto/revert-a-faulty-merge.html
.RE
