'\" t
.\"     Title: git-apply
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-APPLY" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-apply \- Apply a patch to files and/or to the index
.SH "SYNOPSIS"
.sp
.nf
\fIgit apply\fR [\-\-stat] [\-\-numstat] [\-\-summary] [\-\-check] [\-\-index] [\-\-3way]
          [\-\-apply] [\-\-no\-add] [\-\-build\-fake\-ancestor=<file>] [\-R | \-\-reverse]
          [\-\-allow\-binary\-replacement | \-\-binary] [\-\-reject] [\-z]
          [\-p<n>] [\-C<n>] [\-\-inaccurate\-eof] [\-\-recount] [\-\-cached]
          [\-\-ignore\-space\-change | \-\-ignore\-whitespace]
          [\-\-whitespace=(nowarn|warn|fix|error|error\-all)]
          [\-\-exclude=<path>] [\-\-include=<path>] [\-\-directory=<root>]
          [\-\-verbose] [\-\-unsafe\-paths] [<patch>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
Reads the supplied diff output (i\&.e\&. "a patch") and applies it to files\&. When running from a subdirectory in a repository, patched paths outside the directory are ignored\&. With the \fB\-\-index\fR option the patch is also applied to the index, and with the \fB\-\-cached\fR option the patch is only applied to the index\&. Without these options, the command applies the patch only to files, and does not require them to be in a Git repository\&.
.sp
This command applies the patch but does not create a commit\&. Use \fBgit-am\fR(1) to create commits from patches generated by \fBgit-format-patch\fR(1) and/or received by email\&.
.SH "OPTIONS"
.PP
<patch>\&...
.RS 4
The files to read the patch from\&.
\fI\-\fR
can be used to read from the standard input\&.
.RE
.PP
\-\-stat
.RS 4
Instead of applying the patch, output diffstat for the input\&. Turns off "apply"\&.
.RE
.PP
\-\-numstat
.RS 4
Similar to
\fB\-\-stat\fR, but shows the number of added and deleted lines in decimal notation and the pathname without abbreviation, to make it more machine friendly\&. For binary files, outputs two
\fB\-\fR
instead of saying
\fB0 0\fR\&. Turns off "apply"\&.
.RE
.PP
\-\-summary
.RS 4
Instead of applying the patch, output a condensed summary of information obtained from git diff extended headers, such as creations, renames and mode changes\&. Turns off "apply"\&.
.RE
.PP
\-\-check
.RS 4
Instead of applying the patch, see if the patch is applicable to the current working tree and/or the index file and detects errors\&. Turns off "apply"\&.
.RE
.PP
\-\-index
.RS 4
When
\fB\-\-check\fR
is in effect, or when applying the patch (which is the default when none of the options that disables it is in effect), make sure the patch is applicable to what the current index file records\&. If the file to be patched in the working tree is not up to date, it is flagged as an error\&. This flag also causes the index file to be updated\&.
.RE
.PP
\-\-cached
.RS 4
Apply a patch without touching the working tree\&. Instead take the cached data, apply the patch, and store the result in the index without using the working tree\&. This implies
\fB\-\-index\fR\&.
.RE
.PP
\-3, \-\-3way
.RS 4
When the patch does not apply cleanly, fall back on 3\-way merge if the patch records the identity of blobs it is supposed to apply to, and we have those blobs available locally, possibly leaving the conflict markers in the files in the working tree for the user to resolve\&. This option implies the
\fB\-\-index\fR
option, and is incompatible with the
\fB\-\-reject\fR
and the
\fB\-\-cached\fR
options\&.
.RE
.PP
\-\-build\-fake\-ancestor=<file>
.RS 4
Newer
\fIgit diff\fR
output has embedded
\fIindex information\fR
for each blob to help identify the original version that the patch applies to\&. When this flag is given, and if the original versions of the blobs are available locally, builds a temporary index containing those blobs\&.
.sp
When a pure mode change is encountered (which has no index information), the information is read from the current index instead\&.
.RE
.PP
\-R, \-\-reverse
.RS 4
Apply the patch in reverse\&.
.RE
.PP
\-\-reject
.RS 4
For atomicity,
\fIgit apply\fR
by default fails the whole patch and does not touch the working tree when some of the hunks do not apply\&. This option makes it apply the parts of the patch that are applicable, and leave the rejected hunks in corresponding *\&.rej files\&.
.RE
.PP
\-z
.RS 4
When
\fB\-\-numstat\fR
has been given, do not munge pathnames, but use a NUL\-terminated machine\-readable format\&.
.sp
Without this option, pathnames with "unusual" characters are quoted as explained for the configuration variable
\fBcore\&.quotePath\fR
(see
\fBgit-config\fR(1))\&.
.RE
.PP
\-p<n>
.RS 4
Remove <n> leading slashes from traditional diff paths\&. The default is 1\&.
.RE
.PP
\-C<n>
.RS 4
Ensure at least <n> lines of surrounding context match before and after each change\&. When fewer lines of surrounding context exist they all must match\&. By default no context is ever ignored\&.
.RE
.PP
\-\-unidiff\-zero
.RS 4
By default,
\fIgit apply\fR
expects that the patch being applied is a unified diff with at least one line of context\&. This provides good safety measures, but breaks down when applying a diff generated with
\fB\-\-unified=0\fR\&. To bypass these checks use
\fB\-\-unidiff\-zero\fR\&.
.sp
Note, for the reasons stated above usage of context\-free patches is discouraged\&.
.RE
.PP
\-\-apply
.RS 4
If you use any of the options marked "Turns off
\fIapply\fR" above,
\fIgit apply\fR
reads and outputs the requested information without actually applying the patch\&. Give this flag after those flags to also apply the patch\&.
.RE
.PP
\-\-no\-add
.RS 4
When applying a patch, ignore additions made by the patch\&. This can be used to extract the common part between two files by first running
\fIdiff\fR
on them and applying the result with this option, which would apply the deletion part but not the addition part\&.
.RE
.PP
\-\-allow\-binary\-replacement, \-\-binary
.RS 4
Historically we did not allow binary patch applied without an explicit permission from the user, and this flag was the way to do so\&. Currently we always allow binary patch application, so this is a no\-op\&.
.RE
.PP
\-\-exclude=<path\-pattern>
.RS 4
Don\(cqt apply changes to files matching the given path pattern\&. This can be useful when importing patchsets, where you want to exclude certain files or directories\&.
.RE
.PP
\-\-include=<path\-pattern>
.RS 4
Apply changes to files matching the given path pattern\&. This can be useful when importing patchsets, where you want to include certain files or directories\&.
.sp
When
\fB\-\-exclude\fR
and
\fB\-\-include\fR
patterns are used, they are examined in the order they appear on the command line, and the first match determines if a patch to each path is used\&. A patch to a path that does not match any include/exclude pattern is used by default if there is no include pattern on the command line, and ignored if there is any include pattern\&.
.RE
.PP
\-\-ignore\-space\-change, \-\-ignore\-whitespace
.RS 4
When applying a patch, ignore changes in whitespace in context lines if necessary\&. Context lines will preserve their whitespace, and they will not undergo whitespace fixing regardless of the value of the
\fB\-\-whitespace\fR
option\&. New lines will still be fixed, though\&.
.RE
.PP
\-\-whitespace=<action>
.RS 4
When applying a patch, detect a new or modified line that has whitespace errors\&. What are considered whitespace errors is controlled by
\fBcore\&.whitespace\fR
configuration\&. By default, trailing whitespaces (including lines that solely consist of whitespaces) and a space character that is immediately followed by a tab character inside the initial indent of the line are considered whitespace errors\&.
.sp
By default, the command outputs warning messages but applies the patch\&. When
\fBgit\-apply\fR
is used for statistics and not applying a patch, it defaults to
\fBnowarn\fR\&.
.sp
You can use different
\fB<action>\fR
values to control this behavior:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBnowarn\fR
turns off the trailing whitespace warning\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBwarn\fR
outputs warnings for a few such errors, but applies the patch as\-is (default)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBfix\fR
outputs warnings for a few such errors, and applies the patch after fixing them (\fBstrip\fR
is a synonym \-\-\- the tool used to consider only trailing whitespace characters as errors, and the fix involved
\fIstripping\fR
them, but modern Gits do more)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBerror\fR
outputs warnings for a few such errors, and refuses to apply the patch\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBerror\-all\fR
is similar to
\fBerror\fR
but shows all errors\&.
.RE
.RE
.PP
\-\-inaccurate\-eof
.RS 4
Under certain circumstances, some versions of
\fIdiff\fR
do not correctly detect a missing new\-line at the end of the file\&. As a result, patches created by such
\fIdiff\fR
programs do not record incomplete lines correctly\&. This option adds support for applying such patches by working around this bug\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Report progress to stderr\&. By default, only a message about the current patch being applied will be printed\&. This option will cause additional information to be reported\&.
.RE
.PP
\-\-recount
.RS 4
Do not trust the line counts in the hunk headers, but infer them by inspecting the patch (e\&.g\&. after editing the patch without adjusting the hunk headers appropriately)\&.
.RE
.PP
\-\-directory=<root>
.RS 4
Prepend <root> to all filenames\&. If a "\-p" argument was also passed, it is applied before prepending the new root\&.
.sp
For example, a patch that talks about updating
\fBa/git\-gui\&.sh\fR
to
\fBb/git\-gui\&.sh\fR
can be applied to the file in the working tree
\fBmodules/git\-gui/git\-gui\&.sh\fR
by running
\fBgit apply \-\-directory=modules/git\-gui\fR\&.
.RE
.PP
\-\-unsafe\-paths
.RS 4
By default, a patch that affects outside the working area (either a Git controlled working tree, or the current working directory when "git apply" is used as a replacement of GNU patch) is rejected as a mistake (or a mischief)\&.
.sp
When
\fBgit apply\fR
is used as a "better GNU patch", the user can pass the
\fB\-\-unsafe\-paths\fR
option to override this safety check\&. This option has no effect when
\fB\-\-index\fR
or
\fB\-\-cached\fR
is in use\&.
.RE
.SH "CONFIGURATION"
.PP
apply\&.ignoreWhitespace
.RS 4
Set to
\fIchange\fR
if you want changes in whitespace to be ignored by default\&. Set to one of: no, none, never, false if you want changes in whitespace to be significant\&.
.RE
.PP
apply\&.whitespace
.RS 4
When no
\fB\-\-whitespace\fR
flag is given from the command line, this configuration item is used as the default\&.
.RE
.SH "SUBMODULES"
.sp
If the patch contains any changes to submodules then \fIgit apply\fR treats these changes as follows\&.
.sp
If \fB\-\-index\fR is specified (explicitly or implicitly), then the submodule commits must match the index exactly for the patch to apply\&. If any of the submodules are checked\-out, then these check\-outs are completely ignored, i\&.e\&., they are not required to be up to date or clean and they are not updated\&.
.sp
If \fB\-\-index\fR is not specified, then the submodule commits in the patch are ignored and only the absence or presence of the corresponding subdirectory is checked and (if possible) updated\&.
.SH "SEE ALSO"
.sp
\fBgit-am\fR(1)\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
