'\" t
.\"     Title: git-tag
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-TAG" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-tag \- Create, list, delete or verify a tag object signed with GPG
.SH "SYNOPSIS"
.sp
.nf
\fIgit tag\fR [\-a | \-s | \-u <keyid>] [\-f] [\-m <msg> | \-F <file>] [\-e]
        <tagname> [<commit> | <object>]
\fIgit tag\fR \-d <tagname>\&...
\fIgit tag\fR [\-n[<num>]] \-l [\-\-contains <commit>] [\-\-no\-contains <commit>]
        [\-\-points\-at <object>] [\-\-column[=<options>] | \-\-no\-column]
        [\-\-create\-reflog] [\-\-sort=<key>] [\-\-format=<format>]
        [\-\-[no\-]merged [<commit>]] [<pattern>\&...]
\fIgit tag\fR \-v [\-\-format=<format>] <tagname>\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
Add a tag reference in \fBrefs/tags/\fR, unless \fB\-d/\-l/\-v\fR is given to delete, list or verify tags\&.
.sp
Unless \fB\-f\fR is given, the named tag must not yet exist\&.
.sp
If one of \fB\-a\fR, \fB\-s\fR, or \fB\-u <keyid>\fR is passed, the command creates a \fItag\fR object, and requires a tag message\&. Unless \fB\-m <msg>\fR or \fB\-F <file>\fR is given, an editor is started for the user to type in the tag message\&.
.sp
If \fB\-m <msg>\fR or \fB\-F <file>\fR is given and \fB\-a\fR, \fB\-s\fR, and \fB\-u <keyid>\fR are absent, \fB\-a\fR is implied\&.
.sp
Otherwise just a tag reference for the SHA\-1 object name of the commit object is created (i\&.e\&. a lightweight tag)\&.
.sp
A GnuPG signed tag object will be created when \fB\-s\fR or \fB\-u <keyid>\fR is used\&. When \fB\-u <keyid>\fR is not used, the committer identity for the current user is used to find the GnuPG key for signing\&. The configuration variable \fBgpg\&.program\fR is used to specify custom GnuPG binary\&.
.sp
Tag objects (created with \fB\-a\fR, \fB\-s\fR, or \fB\-u\fR) are called "annotated" tags; they contain a creation date, the tagger name and e\-mail, a tagging message, and an optional GnuPG signature\&. Whereas a "lightweight" tag is simply a name for an object (usually a commit object)\&.
.sp
Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels\&. For this reason, some git commands for naming objects (like \fBgit describe\fR) will ignore lightweight tags by default\&.
.SH "OPTIONS"
.PP
\-a, \-\-annotate
.RS 4
Make an unsigned, annotated tag object
.RE
.PP
\-s, \-\-sign
.RS 4
Make a GPG\-signed tag, using the default e\-mail address\(cqs key\&.
.RE
.PP
\-u <keyid>, \-\-local\-user=<keyid>
.RS 4
Make a GPG\-signed tag, using the given key\&.
.RE
.PP
\-f, \-\-force
.RS 4
Replace an existing tag with the given name (instead of failing)
.RE
.PP
\-d, \-\-delete
.RS 4
Delete existing tags with the given names\&.
.RE
.PP
\-v, \-\-verify
.RS 4
Verify the GPG signature of the given tag names\&.
.RE
.PP
\-n<num>
.RS 4
<num> specifies how many lines from the annotation, if any, are printed when using \-l\&. Implies
\fB\-\-list\fR\&.
.sp
The default is not to print any annotation lines\&. If no number is given to
\fB\-n\fR, only the first line is printed\&. If the tag is not annotated, the commit message is displayed instead\&.
.RE
.PP
\-l, \-\-list
.RS 4
List tags\&. With optional
\fB<pattern>\&.\&.\&.\fR, e\&.g\&.
\fBgit tag \-\-list \(aqv\-*\(aq\fR, list only the tags that match the pattern(s)\&.
.sp
Running "git tag" without arguments also lists all tags\&. The pattern is a shell wildcard (i\&.e\&., matched using fnmatch(3))\&. Multiple patterns may be given; if any of them matches, the tag is shown\&.
.sp
This option is implicitly supplied if any other list\-like option such as
\fB\-\-contains\fR
is provided\&. See the documentation for each of those options for details\&.
.RE
.PP
\-\-sort=<key>
.RS 4
Sort based on the key given\&. Prefix
\fB\-\fR
to sort in descending order of the value\&. You may use the \-\-sort=<key> option multiple times, in which case the last key becomes the primary key\&. Also supports "version:refname" or "v:refname" (tag names are treated as versions)\&. The "version:refname" sort order can also be affected by the "versionsort\&.suffix" configuration variable\&. The keys supported are the same as those in
\fBgit for\-each\-ref\fR\&. Sort order defaults to the value configured for the
\fBtag\&.sort\fR
variable if it exists, or lexicographic order otherwise\&. See
\fBgit-config\fR(1)\&.
.RE
.sp
\-\-color[=<when>]: Respect any colors specified in the \fB\-\-format\fR option\&. The \fB<when>\fR field must be one of \fBalways\fR, \fBnever\fR, or \fBauto\fR (if \fB<when>\fR is absent, behave as if \fBalways\fR was given)\&.
.PP
\-i, \-\-ignore\-case
.RS 4
Sorting and filtering tags are case insensitive\&.
.RE
.PP
\-\-column[=<options>], \-\-no\-column
.RS 4
Display tag listing in columns\&. See configuration variable column\&.tag for option syntax\&.\fB\-\-column\fR
and
\fB\-\-no\-column\fR
without options are equivalent to
\fIalways\fR
and
\fInever\fR
respectively\&.
.sp
This option is only applicable when listing tags without annotation lines\&.
.RE
.PP
\-\-contains [<commit>]
.RS 4
Only list tags which contain the specified commit (HEAD if not specified)\&. Implies
\fB\-\-list\fR\&.
.RE
.PP
\-\-no\-contains [<commit>]
.RS 4
Only list tags which don\(cqt contain the specified commit (HEAD if not specified)\&. Implies
\fB\-\-list\fR\&.
.RE
.PP
\-\-merged [<commit>]
.RS 4
Only list tags whose commits are reachable from the specified commit (\fBHEAD\fR
if not specified), incompatible with
\fB\-\-no\-merged\fR\&.
.RE
.PP
\-\-no\-merged [<commit>]
.RS 4
Only list tags whose commits are not reachable from the specified commit (\fBHEAD\fR
if not specified), incompatible with
\fB\-\-merged\fR\&.
.RE
.PP
\-\-points\-at <object>
.RS 4
Only list tags of the given object (HEAD if not specified)\&. Implies
\fB\-\-list\fR\&.
.RE
.PP
\-m <msg>, \-\-message=<msg>
.RS 4
Use the given tag message (instead of prompting)\&. If multiple
\fB\-m\fR
options are given, their values are concatenated as separate paragraphs\&. Implies
\fB\-a\fR
if none of
\fB\-a\fR,
\fB\-s\fR, or
\fB\-u <keyid>\fR
is given\&.
.RE
.PP
\-F <file>, \-\-file=<file>
.RS 4
Take the tag message from the given file\&. Use
\fI\-\fR
to read the message from the standard input\&. Implies
\fB\-a\fR
if none of
\fB\-a\fR,
\fB\-s\fR, or
\fB\-u <keyid>\fR
is given\&.
.RE
.PP
\-e, \-\-edit
.RS 4
The message taken from file with
\fB\-F\fR
and command line with
\fB\-m\fR
are usually used as the tag message unmodified\&. This option lets you further edit the message taken from these sources\&.
.RE
.PP
\-\-cleanup=<mode>
.RS 4
This option sets how the tag message is cleaned up\&. The
\fI<mode>\fR
can be one of
\fIverbatim\fR,
\fIwhitespace\fR
and
\fIstrip\fR\&. The
\fIstrip\fR
mode is default\&. The
\fIverbatim\fR
mode does not change message at all,
\fIwhitespace\fR
removes just leading/trailing whitespace lines and
\fIstrip\fR
removes both whitespace and commentary\&.
.RE
.PP
\-\-create\-reflog
.RS 4
Create a reflog for the tag\&. To globally enable reflogs for tags, see
\fBcore\&.logAllRefUpdates\fR
in
\fBgit-config\fR(1)\&. The negated form
\fB\-\-no\-create\-reflog\fR
only overrides an earlier
\fB\-\-create\-reflog\fR, but currently does not negate the setting of
\fBcore\&.logAllRefUpdates\fR\&.
.RE
.PP
<tagname>
.RS 4
The name of the tag to create, delete, or describe\&. The new tag name must pass all checks defined by
\fBgit-check-ref-format\fR(1)\&. Some of these checks may restrict the characters allowed in a tag name\&.
.RE
.PP
<commit>, <object>
.RS 4
The object that the new tag will refer to, usually a commit\&. Defaults to HEAD\&.
.RE
.PP
<format>
.RS 4
A string that interpolates
\fB%(fieldname)\fR
from a tag ref being shown and the object it points at\&. The format is the same as that of
\fBgit-for-each-ref\fR(1)\&. When unspecified, defaults to
\fB%(refname:strip=2)\fR\&.
.RE
.SH "CONFIGURATION"
.sp
By default, \fIgit tag\fR in sign\-with\-default mode (\-s) will use your committer identity (of the form \fBYour Name <your@email\&.address>\fR) to find a key\&. If you want to use a different default key, you can specify it in the repository configuration as follows:
.sp
.if n \{\
.RS 4
.\}
.nf
[user]
    signingKey = <gpg\-keyid>
.fi
.if n \{\
.RE
.\}
.sp
.sp
\fBpager\&.tag\fR is only respected when listing tags, i\&.e\&., when \fB\-l\fR is used or implied\&. The default is to use a pager\&. See \fBgit-config\fR(1)\&.
.SH "DISCUSSION"
.SS "On Re\-tagging"
.sp
What should you do when you tag a wrong commit and you would want to re\-tag?
.sp
If you never pushed anything out, just re\-tag it\&. Use "\-f" to replace the old one\&. And you\(cqre done\&.
.sp
But if you have pushed things out (or others could just read your repository directly), then others will have already seen the old tag\&. In that case you can do one of two things:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
The sane thing\&. Just admit you screwed up, and use a different name\&. Others have already seen one tag\-name, and if you keep the same name, you may be in the situation that two people both have "version X", but they actually have
\fIdifferent\fR
"X"\(aqs\&. So just call it "X\&.1" and be done with it\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
The insane thing\&. You really want to call the new version "X" too,
\fIeven though\fR
others have already seen the old one\&. So just use
\fIgit tag \-f\fR
again, as if you hadn\(cqt already published the old one\&.
.RE
.sp
However, Git does \fBnot\fR (and it should not) change tags behind users back\&. So if somebody already got the old tag, doing a \fIgit pull\fR on your tree shouldn\(cqt just make them overwrite the old one\&.
.sp
If somebody got a release tag from you, you cannot just change the tag for them by updating your own one\&. This is a big security issue, in that people MUST be able to trust their tag\-names\&. If you really want to do the insane thing, you need to just fess up to it, and tell people that you messed up\&. You can do that by making a very public announcement saying:
.sp
.if n \{\
.RS 4
.\}
.nf
Ok, I messed up, and I pushed out an earlier version tagged as X\&. I
then fixed something, and retagged the *fixed* tree as X again\&.

If you got the wrong tag, and want the new one, please delete
the old one and fetch the new one by doing:

        git tag \-d X
        git fetch origin tag X

to get my updated tag\&.

You can test which tag you have by doing

        git rev\-parse X

which should return 0123456789abcdef\&.\&. if you have the new version\&.

Sorry for the inconvenience\&.
.fi
.if n \{\
.RE
.\}
.sp
.sp
Does this seem a bit complicated? It \fBshould\fR be\&. There is no way that it would be correct to just "fix" it automatically\&. People need to know that their tags might have been changed\&.
.SS "On Automatic following"
.sp
If you are following somebody else\(cqs tree, you are most likely using remote\-tracking branches (eg\&. \fBrefs/remotes/origin/master\fR)\&. You usually want the tags from the other end\&.
.sp
On the other hand, if you are fetching because you would want a one\-shot merge from somebody else, you typically do not want to get tags from there\&. This happens more often for people near the toplevel but not limited to them\&. Mere mortals when pulling from each other do not necessarily want to automatically get private anchor point tags from the other person\&.
.sp
Often, "please pull" messages on the mailing list just provide two pieces of information: a repo URL and a branch name; this is designed to be easily cut&pasted at the end of a \fIgit fetch\fR command line:
.sp
.if n \{\
.RS 4
.\}
.nf
Linus, please pull from

        git://git\&.\&.\&.\&./proj\&.git master

to get the following updates\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
.sp
becomes:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git pull git://git\&.\&.\&.\&./proj\&.git master
.fi
.if n \{\
.RE
.\}
.sp
.sp
In such a case, you do not want to automatically follow the other person\(cqs tags\&.
.sp
One important aspect of Git is its distributed nature, which largely means there is no inherent "upstream" or "downstream" in the system\&. On the face of it, the above example might seem to indicate that the tag namespace is owned by the upper echelon of people and that tags only flow downwards, but that is not the case\&. It only shows that the usage pattern determines who are interested in whose tags\&.
.sp
A one\-shot pull is a sign that a commit history is now crossing the boundary between one circle of people (e\&.g\&. "people who are primarily interested in the networking part of the kernel") who may have their own set of tags (e\&.g\&. "this is the third release candidate from the networking group to be proposed for general consumption with 2\&.6\&.21 release") to another circle of people (e\&.g\&. "people who integrate various subsystem improvements")\&. The latter are usually not interested in the detailed tags used internally in the former group (that is what "internal" means)\&. That is why it is desirable not to follow tags automatically in this case\&.
.sp
It may well be that among networking people, they may want to exchange the tags internal to their group, but in that workflow they are most likely tracking each other\(cqs progress by having remote\-tracking branches\&. Again, the heuristic to automatically follow such tags is a good thing\&.
.SS "On Backdating Tags"
.sp
If you have imported some changes from another VCS and would like to add tags for major releases of your work, it is useful to be able to specify the date to embed inside of the tag object; such data in the tag object affects, for example, the ordering of tags in the gitweb interface\&.
.sp
To set the date used in future tag objects, set the environment variable GIT_COMMITTER_DATE (see the later discussion of possible values; the most common form is "YYYY\-MM\-DD HH:MM")\&.
.sp
For example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ GIT_COMMITTER_DATE="2006\-10\-02 10:31" git tag \-s v1\&.0\&.1
.fi
.if n \{\
.RE
.\}
.sp
.SH "DATE FORMATS"
.sp
The \fBGIT_AUTHOR_DATE\fR, \fBGIT_COMMITTER_DATE\fR environment variables support the following date formats:
.PP
Git internal format
.RS 4
It is
\fB<unix timestamp> <time zone offset>\fR, where
\fB<unix timestamp>\fR
is the number of seconds since the UNIX epoch\&.
\fB<time zone offset>\fR
is a positive or negative offset from UTC\&. For example CET (which is 1 hour ahead of UTC) is
\fB+0100\fR\&.
.RE
.PP
RFC 2822
.RS 4
The standard email format as described by RFC 2822, for example
\fBThu, 07 Apr 2005 22:13:13 +0200\fR\&.
.RE
.PP
ISO 8601
.RS 4
Time and date specified by the ISO 8601 standard, for example
\fB2005\-04\-07T22:13:13\fR\&. The parser accepts a space instead of the
\fBT\fR
character as well\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
In addition, the date part is accepted in the following formats:
\fBYYYY\&.MM\&.DD\fR,
\fBMM/DD/YYYY\fR
and
\fBDD\&.MM\&.YYYY\fR\&.
.sp .5v
.RE
.RE
.SH "SEE ALSO"
.sp
\fBgit-check-ref-format\fR(1)\&. \fBgit-config\fR(1)\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
