'\" t
.\"     Title: git-credential-cache
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-CREDENTIAL\-CAC" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-credential-cache \- Helper to temporarily store passwords in memory
.SH "SYNOPSIS"
.sp
.nf
git config credential\&.helper \(aqcache [options]\(aq
.fi
.sp
.SH "DESCRIPTION"
.sp
This command caches credentials in memory for use by future Git programs\&. The stored credentials never touch the disk, and are forgotten after a configurable timeout\&. The cache is accessible over a Unix domain socket, restricted to the current user by filesystem permissions\&.
.sp
You probably don\(cqt want to invoke this command directly; it is meant to be used as a credential helper by other parts of Git\&. See \fBgitcredentials\fR(7) or \fBEXAMPLES\fR below\&.
.SH "OPTIONS"
.PP
\-\-timeout <seconds>
.RS 4
Number of seconds to cache credentials (default: 900)\&.
.RE
.PP
\-\-socket <path>
.RS 4
Use
\fB<path>\fR
to contact a running cache daemon (or start a new cache daemon if one is not started)\&. Defaults to
\fB$XDG_CACHE_HOME/git/credential/socket\fR
unless
\fB~/\&.git\-credential\-cache/\fR
exists in which case
\fB~/\&.git\-credential\-cache/socket\fR
is used instead\&. If your home directory is on a network\-mounted filesystem, you may need to change this to a local filesystem\&. You must specify an absolute path\&.
.RE
.SH "CONTROLLING THE DAEMON"
.sp
If you would like the daemon to exit early, forgetting all cached credentials before their timeout, you can issue an \fBexit\fR action:
.sp
.if n \{\
.RS 4
.\}
.nf
git credential\-cache exit
.fi
.if n \{\
.RE
.\}
.sp
.SH "EXAMPLES"
.sp
The point of this helper is to reduce the number of times you must type your username or password\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config credential\&.helper cache
$ git push http://example\&.com/repo\&.git
Username: <type your username>
Password: <type your password>

[work for 5 more minutes]
$ git push http://example\&.com/repo\&.git
[your credentials are used automatically]
.fi
.if n \{\
.RE
.\}
.sp
.sp
You can provide options via the credential\&.helper configuration variable (this example drops the cache time to 5 minutes):
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config credential\&.helper \(aqcache \-\-timeout=300\(aq
.fi
.if n \{\
.RE
.\}
.sp
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
