'\" t
.\"     Title: git-sh-i18n
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-SH\-I18N" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-sh-i18n \- Git\(aqs i18n setup code for shell scripts
.SH "SYNOPSIS"
.sp
.nf
\fI\&. "$(git \-\-exec\-path)/git\-sh\-i18n"\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
This is not a command the end user would want to run\&. Ever\&. This documentation is meant for people who are studying the Porcelain\-ish scripts and/or are writing new ones\&.
.sp
The \(aqgit sh\-i18n scriptlet is designed to be sourced (using \fB\&.\fR) by Git\(cqs porcelain programs implemented in shell script\&. It provides wrappers for the GNU \fBgettext\fR and \fBeval_gettext\fR functions accessible through the \fBgettext\&.sh\fR script, and provides pass\-through fallbacks on systems without GNU gettext\&.
.SH "FUNCTIONS"
.PP
gettext
.RS 4
Currently a dummy fall\-through function implemented as a wrapper around
\fBprintf(1)\fR\&. Will be replaced by a real gettext implementation in a later version\&.
.RE
.PP
eval_gettext
.RS 4
Currently a dummy fall\-through function implemented as a wrapper around
\fBprintf(1)\fR
with variables expanded by the
\fBgit-sh-i18n--envsubst\fR(1)
helper\&. Will be replaced by a real gettext implementation in a later version\&.
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
