'\" t
.\"     Title: git-rm
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GIT\-RM" "1" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-rm \- Remove files from the working tree and from the index
.SH "SYNOPSIS"
.sp
.nf
\fIgit rm\fR [\-f | \-\-force] [\-n] [\-r] [\-\-cached] [\-\-ignore\-unmatch] [\-\-quiet] [\-\-] <file>\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
Remove files from the index, or from the working tree and the index\&. \fBgit rm\fR will not remove a file from just your working directory\&. (There is no option to remove a file only from the working tree and yet keep it in the index; use \fB/bin/rm\fR if you want to do that\&.) The files being removed have to be identical to the tip of the branch, and no updates to their contents can be staged in the index, though that default behavior can be overridden with the \fB\-f\fR option\&. When \fB\-\-cached\fR is given, the staged content has to match either the tip of the branch or the file on disk, allowing the file to be removed from just the index\&.
.SH "OPTIONS"
.PP
<file>\&...
.RS 4
Files to remove\&. Fileglobs (e\&.g\&.
\fB*\&.c\fR) can be given to remove all matching files\&. If you want Git to expand file glob characters, you may need to shell\-escape them\&. A leading directory name (e\&.g\&.
\fBdir\fR
to remove
\fBdir/file1\fR
and
\fBdir/file2\fR) can be given to remove all files in the directory, and recursively all sub\-directories, but this requires the
\fB\-r\fR
option to be explicitly given\&.
.RE
.PP
\-f, \-\-force
.RS 4
Override the up\-to\-date check\&.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Don\(cqt actually remove any file(s)\&. Instead, just show if they exist in the index and would otherwise be removed by the command\&.
.RE
.PP
\-r
.RS 4
Allow recursive removal when a leading directory name is given\&.
.RE
.PP
\-\-
.RS 4
This option can be used to separate command\-line options from the list of files, (useful when filenames might be mistaken for command\-line options)\&.
.RE
.PP
\-\-cached
.RS 4
Use this option to unstage and remove paths only from the index\&. Working tree files, whether modified or not, will be left alone\&.
.RE
.PP
\-\-ignore\-unmatch
.RS 4
Exit with a zero status even if no files matched\&.
.RE
.PP
\-q, \-\-quiet
.RS 4
\fBgit rm\fR
normally outputs one line (in the form of an
\fBrm\fR
command) for each file removed\&. This option suppresses that output\&.
.RE
.SH "DISCUSSION"
.sp
The <file> list given to the command can be exact pathnames, file glob patterns, or leading directory names\&. The command removes only the paths that are known to Git\&. Giving the name of a file that you have not told Git about does not remove that file\&.
.sp
File globbing matches across directory boundaries\&. Thus, given two directories \fBd\fR and \fBd2\fR, there is a difference between using \fBgit rm \(aqd*\(aq\fR and \fBgit rm \(aqd/*\(aq\fR, as the former will also remove all of directory \fBd2\fR\&.
.SH "REMOVING FILES THAT HAVE DISAPPEARED FROM THE FILESYSTEM"
.sp
There is no option for \fBgit rm\fR to remove from the index only the paths that have disappeared from the filesystem\&. However, depending on the use case, there are several ways that can be done\&.
.SS "Using \(lqgit commit \-a\(rq"
.sp
If you intend that your next commit should record all modifications of tracked files in the working tree and record all removals of files that have been removed from the working tree with \fBrm\fR (as opposed to \fBgit rm\fR), use \fBgit commit \-a\fR, as it will automatically notice and record all removals\&. You can also have a similar effect without committing by using \fBgit add \-u\fR\&.
.SS "Using \(lqgit add \-A\(rq"
.sp
When accepting a new code drop for a vendor branch, you probably want to record both the removal of paths and additions of new paths as well as modifications of existing paths\&.
.sp
Typically you would first remove all tracked files from the working tree using this command:
.sp
.if n \{\
.RS 4
.\}
.nf
git ls\-files \-z | xargs \-0 rm \-f
.fi
.if n \{\
.RE
.\}
.sp
.sp
and then untar the new code in the working tree\&. Alternately you could \fIrsync\fR the changes into the working tree\&.
.sp
After that, the easiest way to record all removals, additions, and modifications in the working tree is:
.sp
.if n \{\
.RS 4
.\}
.nf
git add \-A
.fi
.if n \{\
.RE
.\}
.sp
.sp
See \fBgit-add\fR(1)\&.
.SS "Other ways"
.sp
If all you really want to do is to remove from the index the files that are no longer present in the working tree (perhaps because your working tree is dirty so that you cannot use \fBgit commit \-a\fR), use the following command:
.sp
.if n \{\
.RS 4
.\}
.nf
git diff \-\-name\-only \-\-diff\-filter=D \-z | xargs \-0 git rm \-\-cached
.fi
.if n \{\
.RE
.\}
.sp
.SH "SUBMODULES"
.sp
Only submodules using a gitfile (which means they were cloned with a Git version 1\&.7\&.8 or newer) will be removed from the work tree, as their repository lives inside the \&.git directory of the superproject\&. If a submodule (or one of those nested inside it) still uses a \&.git directory, \fBgit rm\fR will move the submodules git directory into the superprojects git directory to protect the submodule\(cqs history\&. If it exists the submodule\&.<name> section in the \fBgitmodules\fR(5) file will also be removed and that file will be staged (unless \-\-cached or \-n are used)\&.
.sp
A submodule is considered up to date when the HEAD is the same as recorded in the index, no tracked files are modified and no untracked files that aren\(cqt ignored are present in the submodules work tree\&. Ignored files are deemed expendable and won\(cqt stop a submodule\(cqs work tree from being removed\&.
.sp
If you only want to remove the local checkout of a submodule from your work tree without committing the removal, use \fBgit-submodule\fR(1) \fBdeinit\fR instead\&. Also see \fBgitsubmodules\fR(7) for details on submodule removal\&.
.SH "EXAMPLES"
.PP
\fBgit rm Documentation/\e*\&.txt\fR
.RS 4
Removes all
\fB*\&.txt\fR
files from the index that are under the
\fBDocumentation\fR
directory and any of its subdirectories\&.
.sp
Note that the asterisk
\fB*\fR
is quoted from the shell in this example; this lets Git, and not the shell, expand the pathnames of files and subdirectories under the
\fBDocumentation/\fR
directory\&.
.RE
.PP
\fBgit rm \-f git\-*\&.sh\fR
.RS 4
Because this example lets the shell expand the asterisk (i\&.e\&. you are listing the files explicitly), it does not remove
\fBsubdir/git\-foo\&.sh\fR\&.
.RE
.SH "BUGS"
.sp
Each time a superproject update removes a populated submodule (e\&.g\&. when switching between commits before and after the removal) a stale submodule checkout will remain in the old location\&. Removing the old directory is only safe when it uses a gitfile, as otherwise the history of the submodule will be deleted too\&. This step will be obsolete when recursive submodule update has been implemented\&.
.SH "SEE ALSO"
.sp
\fBgit-add\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
