.\" Copyright (c) 2001 Apple Computer, Inc. All Rights Reserved.
.Dd Oct 6, 2001 
.Dt MVMAC 1
.Os "Mac OS X"
.Sh NAME
.Nm /usr/bin/MvMac
.Nd move files while preserving metadata and forks (DEPRECATED)
.Sh SYNOPSIS
.Nm
.Ar source ... directory
.Sh DESCRIPTION
.Pp
Tools supporting Carbon development, including
.Nm ,
were deprecated with Xcode 6.
.Pp
.Nm
moves each file named by a
.Ar source
operand to a destination file in the existing directory named by the
.Ar directory
operand.
The destination path for each operand is the pathname produced by the
concatenation of the last operand, a slash, and the final pathname
component of the named file.
.Pp
If the destination path does not have a mode that permits writing,
.Nm
will return an error.
.Sh NOTES
The 
.Nm MvMac
command does not support the same options as the POSIX 
.Nm mv
command, and is much less flexible in its operands.  It cannot be used as a direct substitute for 
.Nm mv
in scripts.
.Pp
As of Mac OS X 10.4, the
.Nm mv
command preserves metadata and resource forks of files on Extended HFS volumes, so it can be used in place of 
.Nm MvMac\&.
The 
.Nm MvMac
command will be deprecated in future versions of Mac OS X.
.Sh BUGS
Currently doesn't work across volumes/filesystems.
.Sh SEE ALSO
.Xr mv 1
.Xr CpMac 1
