'\" t
.\"     Title: gittutorial
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2018
.\"    Manual: Git Manual
.\"    Source: Git 2.17.0
.\"  Language: English
.\"
.TH "GITTUTORIAL" "7" "04/02/2018" "Git 2\&.17\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gittutorial \- A tutorial introduction to Git
.SH "SYNOPSIS"
.sp
.nf
git *
.fi
.sp
.SH "DESCRIPTION"
.sp
This tutorial explains how to import a new project into Git, make changes to it, and share changes with other developers\&.
.sp
If you are instead primarily interested in using Git to fetch a project, for example, to test the latest version, you may prefer to start with the first two chapters of \m[blue]\fBThe Git User\(cqs Manual\fR\m[]\&\s-2\u[1]\d\s+2\&.
.sp
First, note that you can get documentation for a command such as \fBgit log \-\-graph\fR with:
.sp
.if n \{\
.RS 4
.\}
.nf
$ man git\-log
.fi
.if n \{\
.RE
.\}
.sp
.sp
or:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git help log
.fi
.if n \{\
.RE
.\}
.sp
.sp
With the latter, you can use the manual viewer of your choice; see \fBgit-help\fR(1) for more information\&.
.sp
It is a good idea to introduce yourself to Git with your name and public email address before doing any operation\&. The easiest way to do so is:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git config \-\-global user\&.name "Your Name Comes Here"
$ git config \-\-global user\&.email you@yourdomain\&.example\&.com
.fi
.if n \{\
.RE
.\}
.sp
.SH "IMPORTING A NEW PROJECT"
.sp
Assume you have a tarball project\&.tar\&.gz with your initial work\&. You can place it under Git revision control as follows\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ tar xzf project\&.tar\&.gz
$ cd project
$ git init
.fi
.if n \{\
.RE
.\}
.sp
.sp
Git will reply
.sp
.if n \{\
.RS 4
.\}
.nf
Initialized empty Git repository in \&.git/
.fi
.if n \{\
.RE
.\}
.sp
.sp
You\(cqve now initialized the working directory\(emyou may notice a new directory created, named "\&.git"\&.
.sp
Next, tell Git to take a snapshot of the contents of all files under the current directory (note the \fI\&.\fR), with \fIgit add\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git add \&.
.fi
.if n \{\
.RE
.\}
.sp
.sp
This snapshot is now stored in a temporary staging area which Git calls the "index"\&. You can permanently store the contents of the index in the repository with \fIgit commit\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git commit
.fi
.if n \{\
.RE
.\}
.sp
.sp
This will prompt you for a commit message\&. You\(cqve now stored the first version of your project in Git\&.
.SH "MAKING CHANGES"
.sp
Modify some files, then add their updated contents to the index:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git add file1 file2 file3
.fi
.if n \{\
.RE
.\}
.sp
.sp
You are now ready to commit\&. You can see what is about to be committed using \fIgit diff\fR with the \-\-cached option:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git diff \-\-cached
.fi
.if n \{\
.RE
.\}
.sp
.sp
(Without \-\-cached, \fIgit diff\fR will show you any changes that you\(cqve made but not yet added to the index\&.) You can also get a brief summary of the situation with \fIgit status\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git status
On branch master
Changes to be committed:
Your branch is up to date with \(aqorigin/master\(aq\&.
  (use "git reset HEAD <file>\&.\&.\&." to unstage)

        modified:   file1
        modified:   file2
        modified:   file3
.fi
.if n \{\
.RE
.\}
.sp
.sp
If you need to make any further adjustments, do so now, and then add any newly modified content to the index\&. Finally, commit your changes with:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git commit
.fi
.if n \{\
.RE
.\}
.sp
.sp
This will again prompt you for a message describing the change, and then record a new version of the project\&.
.sp
Alternatively, instead of running \fIgit add\fR beforehand, you can use
.sp
.if n \{\
.RS 4
.\}
.nf
$ git commit \-a
.fi
.if n \{\
.RE
.\}
.sp
.sp
which will automatically notice any modified (but not new) files, add them to the index, and commit, all in one step\&.
.sp
A note on commit messages: Though not required, it\(cqs a good idea to begin the commit message with a single short (less than 50 character) line summarizing the change, followed by a blank line and then a more thorough description\&. The text up to the first blank line in a commit message is treated as the commit title, and that title is used throughout Git\&. For example, \fBgit-format-patch\fR(1) turns a commit into email, and it uses the title on the Subject line and the rest of the commit in the body\&.
.SH "GIT TRACKS CONTENT NOT FILES"
.sp
Many revision control systems provide an \fBadd\fR command that tells the system to start tracking changes to a new file\&. Git\(cqs \fBadd\fR command does something simpler and more powerful: \fIgit add\fR is used both for new and newly modified files, and in both cases it takes a snapshot of the given files and stages that content in the index, ready for inclusion in the next commit\&.
.SH "VIEWING PROJECT HISTORY"
.sp
At any point you can view the history of your changes using
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log
.fi
.if n \{\
.RE
.\}
.sp
.sp
If you also want to see complete diffs at each step, use
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log \-p
.fi
.if n \{\
.RE
.\}
.sp
.sp
Often the overview of the change is useful to get a feel of each step
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log \-\-stat \-\-summary
.fi
.if n \{\
.RE
.\}
.sp
.SH "MANAGING BRANCHES"
.sp
A single Git repository can maintain multiple branches of development\&. To create a new branch named "experimental", use
.sp
.if n \{\
.RS 4
.\}
.nf
$ git branch experimental
.fi
.if n \{\
.RE
.\}
.sp
.sp
If you now run
.sp
.if n \{\
.RS 4
.\}
.nf
$ git branch
.fi
.if n \{\
.RE
.\}
.sp
.sp
you\(cqll get a list of all existing branches:
.sp
.if n \{\
.RS 4
.\}
.nf
  experimental
* master
.fi
.if n \{\
.RE
.\}
.sp
.sp
The "experimental" branch is the one you just created, and the "master" branch is a default branch that was created for you automatically\&. The asterisk marks the branch you are currently on; type
.sp
.if n \{\
.RS 4
.\}
.nf
$ git checkout experimental
.fi
.if n \{\
.RE
.\}
.sp
.sp
to switch to the experimental branch\&. Now edit a file, commit the change, and switch back to the master branch:
.sp
.if n \{\
.RS 4
.\}
.nf
(edit file)
$ git commit \-a
$ git checkout master
.fi
.if n \{\
.RE
.\}
.sp
.sp
Check that the change you made is no longer visible, since it was made on the experimental branch and you\(cqre back on the master branch\&.
.sp
You can make a different change on the master branch:
.sp
.if n \{\
.RS 4
.\}
.nf
(edit file)
$ git commit \-a
.fi
.if n \{\
.RE
.\}
.sp
.sp
at this point the two branches have diverged, with different changes made in each\&. To merge the changes made in experimental into master, run
.sp
.if n \{\
.RS 4
.\}
.nf
$ git merge experimental
.fi
.if n \{\
.RE
.\}
.sp
.sp
If the changes don\(cqt conflict, you\(cqre done\&. If there are conflicts, markers will be left in the problematic files showing the conflict;
.sp
.if n \{\
.RS 4
.\}
.nf
$ git diff
.fi
.if n \{\
.RE
.\}
.sp
.sp
will show this\&. Once you\(cqve edited the files to resolve the conflicts,
.sp
.if n \{\
.RS 4
.\}
.nf
$ git commit \-a
.fi
.if n \{\
.RE
.\}
.sp
.sp
will commit the result of the merge\&. Finally,
.sp
.if n \{\
.RS 4
.\}
.nf
$ gitk
.fi
.if n \{\
.RE
.\}
.sp
.sp
will show a nice graphical representation of the resulting history\&.
.sp
At this point you could delete the experimental branch with
.sp
.if n \{\
.RS 4
.\}
.nf
$ git branch \-d experimental
.fi
.if n \{\
.RE
.\}
.sp
.sp
This command ensures that the changes in the experimental branch are already in the current branch\&.
.sp
If you develop on a branch crazy\-idea, then regret it, you can always delete the branch with
.sp
.if n \{\
.RS 4
.\}
.nf
$ git branch \-D crazy\-idea
.fi
.if n \{\
.RE
.\}
.sp
.sp
Branches are cheap and easy, so this is a good way to try something out\&.
.SH "USING GIT FOR COLLABORATION"
.sp
Suppose that Alice has started a new project with a Git repository in /home/alice/project, and that Bob, who has a home directory on the same machine, wants to contribute\&.
.sp
Bob begins with:
.sp
.if n \{\
.RS 4
.\}
.nf
bob$ git clone /home/alice/project myrepo
.fi
.if n \{\
.RE
.\}
.sp
.sp
This creates a new directory "myrepo" containing a clone of Alice\(cqs repository\&. The clone is on an equal footing with the original project, possessing its own copy of the original project\(cqs history\&.
.sp
Bob then makes some changes and commits them:
.sp
.if n \{\
.RS 4
.\}
.nf
(edit files)
bob$ git commit \-a
(repeat as necessary)
.fi
.if n \{\
.RE
.\}
.sp
.sp
When he\(cqs ready, he tells Alice to pull changes from the repository at /home/bob/myrepo\&. She does this with:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ cd /home/alice/project
alice$ git pull /home/bob/myrepo master
.fi
.if n \{\
.RE
.\}
.sp
.sp
This merges the changes from Bob\(cqs "master" branch into Alice\(cqs current branch\&. If Alice has made her own changes in the meantime, then she may need to manually fix any conflicts\&.
.sp
The "pull" command thus performs two operations: it fetches changes from a remote branch, then merges them into the current branch\&.
.sp
Note that in general, Alice would want her local changes committed before initiating this "pull"\&. If Bob\(cqs work conflicts with what Alice did since their histories forked, Alice will use her working tree and the index to resolve conflicts, and existing local changes will interfere with the conflict resolution process (Git will still perform the fetch but will refuse to merge \-\-\- Alice will have to get rid of her local changes in some way and pull again when this happens)\&.
.sp
Alice can peek at what Bob did without merging first, using the "fetch" command; this allows Alice to inspect what Bob did, using a special symbol "FETCH_HEAD", in order to determine if he has anything worth pulling, like this:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ git fetch /home/bob/myrepo master
alice$ git log \-p HEAD\&.\&.FETCH_HEAD
.fi
.if n \{\
.RE
.\}
.sp
.sp
This operation is safe even if Alice has uncommitted local changes\&. The range notation "HEAD\&.\&.FETCH_HEAD" means "show everything that is reachable from the FETCH_HEAD but exclude anything that is reachable from HEAD"\&. Alice already knows everything that leads to her current state (HEAD), and reviews what Bob has in his state (FETCH_HEAD) that she has not seen with this command\&.
.sp
If Alice wants to visualize what Bob did since their histories forked she can issue the following command:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gitk HEAD\&.\&.FETCH_HEAD
.fi
.if n \{\
.RE
.\}
.sp
.sp
This uses the same two\-dot range notation we saw earlier with \fIgit log\fR\&.
.sp
Alice may want to view what both of them did since they forked\&. She can use three\-dot form instead of the two\-dot form:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gitk HEAD\&.\&.\&.FETCH_HEAD
.fi
.if n \{\
.RE
.\}
.sp
.sp
This means "show everything that is reachable from either one, but exclude anything that is reachable from both of them"\&.
.sp
Please note that these range notation can be used with both gitk and "git log"\&.
.sp
After inspecting what Bob did, if there is nothing urgent, Alice may decide to continue working without pulling from Bob\&. If Bob\(cqs history does have something Alice would immediately need, Alice may choose to stash her work\-in\-progress first, do a "pull", and then finally unstash her work\-in\-progress on top of the resulting history\&.
.sp
When you are working in a small closely knit group, it is not unusual to interact with the same repository over and over again\&. By defining \fIremote\fR repository shorthand, you can make it easier:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ git remote add bob /home/bob/myrepo
.fi
.if n \{\
.RE
.\}
.sp
.sp
With this, Alice can perform the first part of the "pull" operation alone using the \fIgit fetch\fR command without merging them with her own branch, using:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ git fetch bob
.fi
.if n \{\
.RE
.\}
.sp
.sp
Unlike the longhand form, when Alice fetches from Bob using a remote repository shorthand set up with \fIgit remote\fR, what was fetched is stored in a remote\-tracking branch, in this case \fBbob/master\fR\&. So after this:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ git log \-p master\&.\&.bob/master
.fi
.if n \{\
.RE
.\}
.sp
.sp
shows a list of all the changes that Bob made since he branched from Alice\(cqs master branch\&.
.sp
After examining those changes, Alice could merge the changes into her master branch:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ git merge bob/master
.fi
.if n \{\
.RE
.\}
.sp
.sp
This \fBmerge\fR can also be done by \fIpulling from her own remote\-tracking branch\fR, like this:
.sp
.if n \{\
.RS 4
.\}
.nf
alice$ git pull \&. remotes/bob/master
.fi
.if n \{\
.RE
.\}
.sp
.sp
Note that git pull always merges into the current branch, regardless of what else is given on the command line\&.
.sp
Later, Bob can update his repo with Alice\(cqs latest changes using
.sp
.if n \{\
.RS 4
.\}
.nf
bob$ git pull
.fi
.if n \{\
.RE
.\}
.sp
.sp
Note that he doesn\(cqt need to give the path to Alice\(cqs repository; when Bob cloned Alice\(cqs repository, Git stored the location of her repository in the repository configuration, and that location is used for pulls:
.sp
.if n \{\
.RS 4
.\}
.nf
bob$ git config \-\-get remote\&.origin\&.url
/home/alice/project
.fi
.if n \{\
.RE
.\}
.sp
.sp
(The complete configuration created by \fIgit clone\fR is visible using \fBgit config \-l\fR, and the \fBgit-config\fR(1) man page explains the meaning of each option\&.)
.sp
Git also keeps a pristine copy of Alice\(cqs master branch under the name "origin/master":
.sp
.if n \{\
.RS 4
.\}
.nf
bob$ git branch \-r
  origin/master
.fi
.if n \{\
.RE
.\}
.sp
.sp
If Bob later decides to work from a different host, he can still perform clones and pulls using the ssh protocol:
.sp
.if n \{\
.RS 4
.\}
.nf
bob$ git clone alice\&.org:/home/alice/project myrepo
.fi
.if n \{\
.RE
.\}
.sp
.sp
Alternatively, Git has a native protocol, or can use http; see \fBgit-pull\fR(1) for details\&.
.sp
Git can also be used in a CVS\-like mode, with a central repository that various users push changes to; see \fBgit-push\fR(1) and \fBgitcvs-migration\fR(7)\&.
.SH "EXPLORING HISTORY"
.sp
Git history is represented as a series of interrelated commits\&. We have already seen that the \fIgit log\fR command can list those commits\&. Note that first line of each git log entry also gives a name for the commit:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log
commit c82a22c39cbc32576f64f5c6b3f24b99ea8149c7
Author: Junio C Hamano <junkio@cox\&.net>
Date:   Tue May 16 17:18:22 2006 \-0700

    merge\-base: Clarify the comments on post processing\&.
.fi
.if n \{\
.RE
.\}
.sp
.sp
We can give this name to \fIgit show\fR to see the details about this commit\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ git show c82a22c39cbc32576f64f5c6b3f24b99ea8149c7
.fi
.if n \{\
.RE
.\}
.sp
.sp
But there are other ways to refer to commits\&. You can use any initial part of the name that is long enough to uniquely identify the commit:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git show c82a22c39c   # the first few characters of the name are
                        # usually enough
$ git show HEAD         # the tip of the current branch
$ git show experimental # the tip of the "experimental" branch
.fi
.if n \{\
.RE
.\}
.sp
.sp
Every commit usually has one "parent" commit which points to the previous state of the project:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git show HEAD^  # to see the parent of HEAD
$ git show HEAD^^ # to see the grandparent of HEAD
$ git show HEAD~4 # to see the great\-great grandparent of HEAD
.fi
.if n \{\
.RE
.\}
.sp
.sp
Note that merge commits may have more than one parent:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git show HEAD^1 # show the first parent of HEAD (same as HEAD^)
$ git show HEAD^2 # show the second parent of HEAD
.fi
.if n \{\
.RE
.\}
.sp
.sp
You can also give commits names of your own; after running
.sp
.if n \{\
.RS 4
.\}
.nf
$ git tag v2\&.5 1b2e1d63ff
.fi
.if n \{\
.RE
.\}
.sp
.sp
you can refer to 1b2e1d63ff by the name "v2\&.5"\&. If you intend to share this name with other people (for example, to identify a release version), you should create a "tag" object, and perhaps sign it; see \fBgit-tag\fR(1) for details\&.
.sp
Any Git command that needs to know a commit can take any of these names\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git diff v2\&.5 HEAD     # compare the current HEAD to v2\&.5
$ git branch stable v2\&.5 # start a new branch named "stable" based
                         # at v2\&.5
$ git reset \-\-hard HEAD^ # reset your current branch and working
                         # directory to its state at HEAD^
.fi
.if n \{\
.RE
.\}
.sp
.sp
Be careful with that last command: in addition to losing any changes in the working directory, it will also remove all later commits from this branch\&. If this branch is the only branch containing those commits, they will be lost\&. Also, don\(cqt use \fIgit reset\fR on a publicly\-visible branch that other developers pull from, as it will force needless merges on other developers to clean up the history\&. If you need to undo changes that you have pushed, use \fIgit revert\fR instead\&.
.sp
The \fIgit grep\fR command can search for strings in any version of your project, so
.sp
.if n \{\
.RS 4
.\}
.nf
$ git grep "hello" v2\&.5
.fi
.if n \{\
.RE
.\}
.sp
.sp
searches for all occurrences of "hello" in v2\&.5\&.
.sp
If you leave out the commit name, \fIgit grep\fR will search any of the files it manages in your current directory\&. So
.sp
.if n \{\
.RS 4
.\}
.nf
$ git grep "hello"
.fi
.if n \{\
.RE
.\}
.sp
.sp
is a quick way to search just the files that are tracked by Git\&.
.sp
Many Git commands also take sets of commits, which can be specified in a number of ways\&. Here are some examples with \fIgit log\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log v2\&.5\&.\&.v2\&.6            # commits between v2\&.5 and v2\&.6
$ git log v2\&.5\&.\&.                # commits since v2\&.5
$ git log \-\-since="2 weeks ago" # commits from the last 2 weeks
$ git log v2\&.5\&.\&. Makefile       # commits since v2\&.5 which modify
                                # Makefile
.fi
.if n \{\
.RE
.\}
.sp
.sp
You can also give \fIgit log\fR a "range" of commits where the first is not necessarily an ancestor of the second; for example, if the tips of the branches "stable" and "master" diverged from a common commit some time ago, then
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log stable\&.\&.master
.fi
.if n \{\
.RE
.\}
.sp
.sp
will list commits made in the master branch but not in the stable branch, while
.sp
.if n \{\
.RS 4
.\}
.nf
$ git log master\&.\&.stable
.fi
.if n \{\
.RE
.\}
.sp
.sp
will show the list of commits made on the stable branch but not the master branch\&.
.sp
The \fIgit log\fR command has a weakness: it must present commits in a list\&. When the history has lines of development that diverged and then merged back together, the order in which \fIgit log\fR presents those commits is meaningless\&.
.sp
Most projects with multiple contributors (such as the Linux kernel, or Git itself) have frequent merges, and \fIgitk\fR does a better job of visualizing their history\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
$ gitk \-\-since="2 weeks ago" drivers/
.fi
.if n \{\
.RE
.\}
.sp
.sp
allows you to browse any commits from the last 2 weeks of commits that modified files under the "drivers" directory\&. (Note: you can adjust gitk\(cqs fonts by holding down the control key while pressing "\-" or "+"\&.)
.sp
Finally, most commands that take filenames will optionally allow you to precede any filename by a commit, to specify a particular version of the file:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git diff v2\&.5:Makefile HEAD:Makefile\&.in
.fi
.if n \{\
.RE
.\}
.sp
.sp
You can also use \fIgit show\fR to see any such file:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git show v2\&.5:Makefile
.fi
.if n \{\
.RE
.\}
.sp
.SH "NEXT STEPS"
.sp
This tutorial should be enough to perform basic distributed revision control for your projects\&. However, to fully understand the depth and power of Git you need to understand two simple ideas on which it is based:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The object database is the rather elegant system used to store the history of your project\(emfiles, directories, and commits\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The index file is a cache of the state of a directory tree, used to create commits, check out working directories, and hold the various trees involved in a merge\&.
.RE
.sp
Part two of this tutorial explains the object database, the index file, and a few other odds and ends that you\(cqll need to make the most of Git\&. You can find it at \fBgittutorial-2\fR(7)\&.
.sp
If you don\(cqt want to continue with that right away, a few other digressions that may be interesting at this point are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgit-format-patch\fR(1),
\fBgit-am\fR(1): These convert series of git commits into emailed patches, and vice versa, useful for projects such as the Linux kernel which rely heavily on emailed patches\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgit-bisect\fR(1): When there is a regression in your project, one way to track down the bug is by searching through the history to find the exact commit that\(cqs to blame\&. Git bisect can help you perform a binary search for that commit\&. It is smart enough to perform a close\-to\-optimal search even in the case of complex non\-linear history with lots of merged branches\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgitworkflows\fR(7): Gives an overview of recommended workflows\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgiteveryday\fR(7): Everyday Git with 20 Commands Or So\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgitcvs-migration\fR(7): Git for CVS users\&.
.RE
.SH "SEE ALSO"
.sp
\fBgittutorial-2\fR(7), \fBgitcvs-migration\fR(7), \fBgitcore-tutorial\fR(7), \fBgitglossary\fR(7), \fBgit-help\fR(1), \fBgitworkflows\fR(7), \fBgiteveryday\fR(7), \m[blue]\fBThe Git User\(cqs Manual\fR\m[]\&\s-2\u[1]\d\s+2
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
.SH "NOTES"
.IP " 1." 4
The Git User\(cqs Manual
.RS 4
\%git-htmldocs/user-manual.html
.RE
